### PR TITLE
Make option screen more compact

### PR DESCRIPTION
**Pull request by risostk**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by luffah** [comment]
I agree for most of change except for the modification of drone chase camera that shall be stable in option_screen_ui.cpp.  The smoothing option is not well used by SuperTuxKart when distance and angle are not the standard one. You can see the angle is < 20deg when smoothing is activated on drone chase cam. Therefore i prefer not to expose this setting.

Anyone can propose an alternative cam setting with right angle and without something on one hand. And in the other hand proposed a correction of camera smoothing function in a future PR.

**Review by luffah — DISMISSED** [review]
Thank for the other correction (coding style and description).
Some fix to do on checkboxes.

**Comment by luffah** [comment]
lol. it take me more time to resolve merge conflicts than doing it myself.

**Comment by risostk** [comment]
Glad it helped!

**Pull request merged**
